<a href="https://colab.research.google.com/github/sidchaubey/shala2020/blob/master/Numpy_Part_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Performing Operations on numpy array
a = np.arange(10)
b = a*2
print(b)

[ 0  2  4  6  8 10 12 14 16 18]


In [2]:
c = a+2
print(c)

[ 2  3  4  5  6  7  8  9 10 11]


In [3]:
# But if we add two vector of same size then it computes element wise operation
d = b+c
print(d)

[ 2  5  8 11 14 17 20 23 26 29]


In [5]:
print(a==b)# This check whether each single item in element a  is equal to each item in element b and returns corresponding True or False value
print(a!=b)

[ True False False False False False False False False False]
[False  True  True  True  True  True  True  True  True  True]


In [9]:
# To check whole array at a time we use array_equals
np.array_equal(a,b)

False

In [10]:
# To perform logical and operator
np.logical_and(a,b)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
np.logical_or(a,b)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
np.logical_not(a)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [14]:
np.logical_xor(a,b)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
# Using mask to create indexing
print(a)
mask= [0,2,4,6,8]# Selecting only the even indices
print(a[mask])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [46]:
# BroadCasting
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
# In-build functions
print(a)
a.sum()# This computes overall sum

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


120

In [30]:
print(a.sum(axis=0))# Column wise sum
a.sum(axis=1)# row wise sum

[24 28 32 36]


array([ 6, 22, 38, 54])

In [32]:
print(np.sin(a))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]]


In [33]:
print(np.cos(a))

[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]
 [ 0.84385396  0.90744678  0.13673722 -0.75968791]]


In [34]:
np.mean(a)

7.5

In [35]:
np.mean(a,axis=1)# row wise

array([ 1.5,  5.5,  9.5, 13.5])

In [36]:
np.mean(a,axis=0)

array([6., 7., 8., 9.])

In [37]:
np.median(a,axis=1)# row wise

array([ 1.5,  5.5,  9.5, 13.5])

In [48]:
from scipy.stats import mode
mode(a,axis=1)

ModeResult(mode=array([[ 0],
       [ 4],
       [ 8],
       [12]]), count=array([[1],
       [1],
       [1],
       [1]]))

In [50]:
mode(a, axis=0)

ModeResult(mode=array([[0, 1, 2, 3]]), count=array([[1, 1, 1, 1]]))

In [49]:
mode(a)

ModeResult(mode=array([[0, 1, 2, 3]]), count=array([[1, 1, 1, 1]]))

In [56]:
a = np.random.randint(1,10,16).reshape(4,4)
print(a)

[[6 9 8 7]
 [9 4 2 7]
 [8 5 5 9]
 [6 1 6 2]]


In [60]:
print(a.max())
a.argmin()

9


13

In [62]:
a.argmax(axis=0)

array([1, 0, 0, 2])

In [63]:
a.argmax(axis=1)

array([1, 0, 3, 0])

In [61]:
a.argmin(axis=1)

array([0, 2, 1, 1])

In [66]:
# Logical operation
print(np.all([True,True,True]))

True


In [67]:
print(np.any([True,True,True]))

True


In [68]:
print(np.all([True,True,False]))

False


In [69]:
print(np.any([True,False,False]))

True


In [70]:
print(np.all([False,False,False]))

False


In [71]:
print(np.any([False,False,False]))

False


In [72]:
print(np.all(a>0))

True


In [73]:
a = np.random.randint(1,100,10)
print("a: ",a)
b = np.random.randint(1,100,10)
print("b: \n",b)
c = np.random.randint(1,100,10)
print("c: \n",c)

a:  [70  4  4 25 55 11 43 80 89 90]
b: 
 [82 27 53  3 15 41 45 40 86 65]
c: 
 [98 80 31 78  2 13 26 99 26 71]


In [75]:
print((a>c) & (a<b).any())

[False False False False  True False  True False  True  True]


In [82]:
# Broadcasting
# Case 1:
a = np.random.randint(1,100,16).reshape(4,4) # we can also use np.tile((1,2,3,4),(4,1))
print("a: \n",a)
b = np.random.randint(1,100,16).reshape(4,4)
print("b: \n",b)
print("a+b: \n",a+b)

a: 
 [[66  4 63 94]
 [43 83 65 19]
 [41 42 52 59]
 [99 93 83 96]]
b: 
 [[27 91 91 87]
 [27 67 54 81]
 [52 90 26  2]
 [29 32 36 94]]
a+b: 
 [[ 93  95 154 181]
 [ 70 150 119 100]
 [ 93 132  78  61]
 [128 125 119 190]]


In [78]:
# Case 2:
a = np.random.randint(1,100,4).reshape(4,)
print("a: \n",a)
b = np.random.randint(1,100,16).reshape(4,4)
print("b: \n",b)
print("a+b: \n",a+b)

a: 
 [19 73 89 77]
b: 
 [[46 87 58  9]
 [12 78 91 22]
 [97 38 96 67]
 [63 36  9 81]]
a+b: 
 [[ 65 160 147  86]
 [ 31 151 180  99]
 [116 111 185 144]
 [ 82 109  98 158]]


In [81]:
# Case 3:
a = np.random.randint(1,100,4).reshape(4,)
a = a[:,np.newaxis]
print("a: \n",a)
b = np.random.randint(1,100,4).reshape(4,)
print("b: \n",b)
print("a+b: \n",a+b)

a: 
 [[71]
 [20]
 [ 9]
 [26]]
b: 
 [85 12 39 16]
a+b: 
 [[156  83 110  87]
 [105  32  59  36]
 [ 94  21  48  25]
 [111  38  65  42]]


In [85]:
# Flattening
a = np.arange(10).reshape(2,5)
print("Before flattening a: \n",a)
a = np.ravel(a)
print("After flattening a: ",a)

Before flattening a: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
After flattening a:  [0 1 2 3 4 5 6 7 8 9]


In [86]:
# Sorting
a = np.random.randint(1,100,10)
print("Before Sorting: ",a)
print("After Sorting: ",np.sort(a))

Before Sorting:  [21 96 98  8 42 77 25 48 68 40]
After Sorting:  [ 8 21 25 40 42 48 68 77 96 98]


In [88]:
a = np.random.randint(1,100,10).reshape(2,5)
print("Before Sorting: \n",a)
print("After Sorting: \n",np.sort(a,axis=0))

Before Sorting: 
 [[80 58 61  1 42]
 [42 85 76 98 24]]
After Sorting: 
 [[42 58 61  1 24]
 [80 85 76 98 42]]


In [89]:
a = np.random.randint(1,100,10).reshape(2,5)
print("Before Sorting: \n",a)
print("After Sorting: \n",np.sort(a,axis=1))

Before Sorting: 
 [[67 87 58 82  9]
 [29  4 65 63 35]]
After Sorting: 
 [[ 9 58 67 82 87]
 [ 4 29 35 63 65]]


In [90]:
a = np.random.randint(1,100,10).reshape(2,5)
print("Before Sorting: \n",a)
print("After Sorting: \n",np.argsort(a,axis=0))

Before Sorting: 
 [[69 95 80 44 71]
 [12 55 58 94 27]]
After Sorting: 
 [[1 1 1 0 1]
 [0 0 0 1 0]]


In [92]:
a = np.random.randint(1,100,10).reshape(2,5)
print("Before Sorting: \n",a)
print("After Sorting: \n",np.argsort(a,axis=0))

Before Sorting: 
 [[ 4 82 19  7 37]
 [96 23  5 80 15]]
After Sorting: 
 [[0 1 1 0 1]
 [1 0 0 1 0]]
